Debug: false
AppName:
HttpServer:
  Port: ":18199"
  AllowCrossDomain: false

Token:
  Sign: "mobgi-game"
  ExpiresAt: 259200

Mysql:
  Host: "127.0.0.1"
  Port: 3306
  Database: ""
  Prefix: ""
  Username: ""
  Password: ""
  Charset: "utf8mb4"
  SetMaxIdleConns: 10
  SetMaxOpenConns: 128
  SetConnMaxLifetime: 60
  ReadWrite: 0 # 1开启，0关闭
  SlowQuery: 2 # 慢 SQL

Redis:
  Host: "127.0.0.1:6379"
  Password:
  Db: 0
  KeyPrefix: "mobgi:game:"
  ExpireTime: 3600

Logs:
  LogName: "/storage/logs/sys.log"
  TextFormat: "json"
  TimePrecision: "millisecond" #记录日志时，相关的时间精度，该参数选项：second  、 millisecond ， 分别表示 秒 和 毫秒 ,默认为毫秒级别
  MaxSize: 10 #每个日志的最大尺寸(以MB为单位）， 超过该值，系统将会自动进行切割
  MaxBackups: 7 #保留旧日志最大个数
  MaxAge: 15 #保留旧日志最大天数
  Compress: false #日志备份时，是否进行压缩

AdsTxt: "google.com, pub-6230025462157662, DIRECT, f08c47fec0942fa0"

BoxKeys:
  Box01:
    Key: ""
    EKey: ""